language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install python"
  - "pip install -r python/requirements.txt"
# command to run tests
script: dev/run-tests